version: "3"


services:
  app:
    build: ./app/
    network_mode: "host"
    image: jhartway99/super-chat-server
    develop:
      watch:
        - action: rebuild
          path: ./app
          target: /app




